# tmux config for Estonian keyboard layout
set -g default-terminal "tmux-256color"
set -s extended-keys always
set -g xterm-keys on
set -as terminal-features ',xterm-256color:extkeys'

# Easier splits
unbind %
unbind '"'
bind-key '|' split-window -h
bind-key '-' split-window -v

# Move between panes with arrow keys
bind Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R
